
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMZEntities
{

using System;
    using System.Collections.Generic;
    
public partial class NotaZakatDetail
{

    public int ID { get; set; }

    public int NotaZakatID { get; set; }

    public int TypeOfZakatID { get; set; }

    public decimal Nominal { get; set; }

    public decimal Jumlah { get; set; }

    public decimal Total { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public bool RowStatus { get; set; }



    public NotaZakat NotaZakat { get; set; }

    public TypeOfZakat TypeOfZakat { get; set; }

}

}
