

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMZEntities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SMZEntities : DbContext
{
    public SMZEntities()
        : base("name=SMZEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Customer> Customers { get; set; }

    public DbSet<Family> Families { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<NotaZakat> NotaZakats { get; set; }

    public DbSet<TypeOfZakat> TypeOfZakats { get; set; }

    public DbSet<NotaZakatDetail> NotaZakatDetails { get; set; }

    public DbSet<ProductClass> ProductClasses { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<ProductHistory> ProductHistories { get; set; }

    public DbSet<NotaDetail> NotaDetails { get; set; }

    public DbSet<Vendor> Vendors { get; set; }

    public DbSet<Nota> Notas { get; set; }

}

}

