//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public application_user()
        {
            this.approval_detail = new HashSet<approval_detail>();
            this.audit_trail = new HashSet<audit_trail>();
            this.temporary_manager = new HashSet<temporary_manager>();
            this.temporary_manager1 = new HashSet<temporary_manager>();
        }
    
        public string id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public string owner_id { get; set; }
        public string app_username { get; set; }
        public string app_password { get; set; }
        public string app_fullname { get; set; }
        public Nullable<bool> is_system_administrator { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string manager_id { get; set; }
        public string primary_team { get; set; }
        public string access_token { get; set; }
        public Nullable<System.DateTime> token_expiry { get; set; }
        public string thumbnail_base64 { get; set; }
        public string photo_base64 { get; set; }
        public string mime_type { get; set; }
        public string business_unit_id { get; set; }
        public string organization_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval_detail> approval_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<audit_trail> audit_trail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temporary_manager> temporary_manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temporary_manager> temporary_manager1 { get; set; }
    }
}
