//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_trail
    {
        public string id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public string owner_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public string organization_id { get; set; }
        public string organization_name { get; set; }
        public string application_user_id { get; set; }
        public string app_username { get; set; }
        public string app_fullname { get; set; }
        public string application_entity_id { get; set; }
        public string user_action { get; set; }
        public string record_id { get; set; }
        public string old_record { get; set; }
        public string old_view { get; set; }
        public string new_record { get; set; }
        public string new_view { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual application_entity application_entity { get; set; }
        public virtual application_user application_user { get; set; }
        public virtual organization organization { get; set; }
    }
}
