//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_brief
    {
        public string id { get; set; }
        public string campaign_id { get; set; }
        public string campaign_type_id { get; set; }
        public string bussiness_type_id { get; set; }
        public string external_brand_id { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<System.DateTime> final_delivery { get; set; }
        public string nationality_id { get; set; }
        public string job_category_id { get; set; }
        public string client_brief_file_id { get; set; }
        public string assigment_id { get; set; }
        public Nullable<long> campaign_progress_id { get; set; }
        public Nullable<System.DateTime> start_campaign { get; set; }
        public Nullable<System.DateTime> finish_campaign { get; set; }
        public Nullable<long> responsible_person { get; set; }
        public Nullable<long> job_pe_id { get; set; }
        public Nullable<long> proposal_file_id { get; set; }
        public Nullable<long> campaign_status_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string business_unit_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
