//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_basic_info
    {
        public string id { get; set; }
        public string employee_code { get; set; }
        public string name_employee { get; set; }
        public string kitas_number { get; set; }
        public Nullable<System.DateTime> kitas_expiry { get; set; }
        public string religion_id { get; set; }
        public string passport_number { get; set; }
        public Nullable<System.DateTime> passport_expiry { get; set; }
        public string npwp_number { get; set; }
        public string npwp_expiry { get; set; }
        public string blood { get; set; }
        public string identity_card { get; set; }
        public string kk_no { get; set; }
        public string post_code { get; set; }
        public string address_identity_card { get; set; }
        public string photo { get; set; }
        public string home_address { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public string reports_to { get; set; }
        public string bpjs_healthy { get; set; }
        public string payroll_methods { get; set; }
        public string position_id { get; set; }
        public string central_resource_id { get; set; }
        public string legal_entity_id { get; set; }
        public string status_employee_id { get; set; }
        public string group { get; set; }
        public string job_level_id { get; set; }
        public string business_unit_id { get; set; }
        public string departement_id { get; set; }
        public string employement_status_id { get; set; }
        public string city_id { get; set; }
        public string account_no { get; set; }
        public string bpjs_tk { get; set; }
        public string married_status_id { get; set; }
        public string last_education { get; set; }
        public string probation { get; set; }
        public string approval { get; set; }
        public string process_salary { get; set; }
        public string job_grade { get; set; }
        public string type_tax { get; set; }
        public Nullable<System.DateTime> warning_date { get; set; }
        public string working_status { get; set; }
        public Nullable<System.DateTime> date_termination { get; set; }
        public string termination_reason { get; set; }
        public string flag_diageo { get; set; }
        public string personal_files { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nick_name { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string birth_place { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public string phone_number { get; set; }
        public string mobile_number { get; set; }
        public string portfolio { get; set; }
        public string pay_slip { get; set; }
        public string location { get; set; }
        public string nationality_id { get; set; }
        public string location_id { get; set; }
        public string job_title_id { get; set; }
        public string bank_id { get; set; }
        public string bank_branch { get; set; }
        public string bank_address { get; set; }
        public string account_name { get; set; }
        public string bank_city { get; set; }
        public string identity_address { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
