//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class hiring_request
    {
        public string id { get; set; }
        public string code { get; set; }
        public string employee_basic_info_id { get; set; }
        public string mpp_id { get; set; }
        public string basic_info_grade_tittle { get; set; }
        public string ttf { get; set; }
        public string employment_status { get; set; }
        public Nullable<double> mpp_budged { get; set; }
        public Nullable<System.DateTime> date_fulfilment { get; set; }
        public string candidate_qualification { get; set; }
        public string hiring_type { get; set; }
        public string approval_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
