//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_pe
    {
        public string id { get; set; }
        public string job_detail_id { get; set; }
        public string job_pa_id { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> pe_cost { get; set; }
        public Nullable<double> margin { get; set; }
        public string approval_id { get; set; }
        public string submitted_by { get; set; }
        public Nullable<int> pe_number { get; set; }
        public Nullable<System.DateTime> pe_date { get; set; }
        public Nullable<int> pe_line_item { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string file_id { get; set; }
        public string child_pce_number { get; set; }
        public string ca_number { get; set; }
        public string proc_number { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
