//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_posting_requisition
    {
        public string id { get; set; }
        public string code { get; set; }
        public string reg_code { get; set; }
        public string status { get; set; }
        public string job_post_description { get; set; }
        public string job_title { get; set; }
        public string client_brief_id { get; set; }
        public Nullable<int> number_of_position { get; set; }
        public Nullable<int> candidate_age_range_start { get; set; }
        public Nullable<int> candidate_age_range_end { get; set; }
        public Nullable<int> salary_start { get; set; }
        public Nullable<int> salary_end { get; set; }
        public string candidate_qualification { get; set; }
        public string candidate_experience { get; set; }
        public string notes { get; set; }
        public string central_resource_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string business_unit_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
