//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_pa
    {
        public string id { get; set; }
        public string job_detail_id { get; set; }
        public string pa_number { get; set; }
        public string mother_pca { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> pa_cost { get; set; }
        public Nullable<decimal> ppn { get; set; }
        public Nullable<decimal> asf { get; set; }
        public Nullable<decimal> pph { get; set; }
        public Nullable<double> margin { get; set; }
        public Nullable<System.DateTime> pa_date { get; set; }
        public string rate_card_id { get; set; }
        public string approval_id { get; set; }
        public string department { get; set; }
        public string division { get; set; }
        public Nullable<int> hour_per_day { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
