//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhoenixDBUltimateEntities : DbContext
    {
        public PhoenixDBUltimateEntities()
            : base("name=PhoenixDBUltimateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affiliation> affiliations { get; set; }
        public virtual DbSet<affiliation_member> affiliation_member { get; set; }
        public virtual DbSet<application_entity> application_entity { get; set; }
        public virtual DbSet<application_menu> application_menu { get; set; }
        public virtual DbSet<application_menu_category> application_menu_category { get; set; }
        public virtual DbSet<application_menu_group> application_menu_group { get; set; }
        public virtual DbSet<application_role> application_role { get; set; }
        public virtual DbSet<application_user> application_user { get; set; }
        public virtual DbSet<approval> approvals { get; set; }
        public virtual DbSet<approval_detail> approval_detail { get; set; }
        public virtual DbSet<approval_group> approval_group { get; set; }
        public virtual DbSet<approval_status> approval_status { get; set; }
        public virtual DbSet<audit_trail> audit_trail { get; set; }
        public virtual DbSet<business_unit> business_unit { get; set; }
        public virtual DbSet<business_unit_type> business_unit_type { get; set; }
        public virtual DbSet<central_resource> central_resource { get; set; }
        public virtual DbSet<central_resources_staff> central_resources_staff { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<entity> entities { get; set; }
        public virtual DbSet<filemaster> filemasters { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_category> item_category { get; set; }
        public virtual DbSet<legal_entity> legal_entity { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<organization_type> organization_type { get; set; }
        public virtual DbSet<role_access> role_access { get; set; }
        public virtual DbSet<role_access_menu> role_access_menu { get; set; }
        public virtual DbSet<salutation> salutations { get; set; }
        public virtual DbSet<shared_record> shared_record { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<team_member> team_member { get; set; }
        public virtual DbSet<team_role> team_role { get; set; }
        public virtual DbSet<temporary_manager> temporary_manager { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<account_group> account_group { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_brand> company_brand { get; set; }
        public virtual DbSet<cost_sharing_allocation> cost_sharing_allocation { get; set; }
        public virtual DbSet<cost_sharing_allocation_detail> cost_sharing_allocation_detail { get; set; }
        public virtual DbSet<purchase_order> purchase_order { get; set; }
        public virtual DbSet<purchase_order_detail> purchase_order_detail { get; set; }
        public virtual DbSet<sales_order> sales_order { get; set; }
        public virtual DbSet<sales_order_detail> sales_order_detail { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transaction_detail> transaction_detail { get; set; }
        public virtual DbSet<achievement> achievements { get; set; }
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<bank_branch> bank_branch { get; set; }
        public virtual DbSet<basic_info_grade_tittle> basic_info_grade_tittle { get; set; }
        public virtual DbSet<basic_salary> basic_salary { get; set; }
        public virtual DbSet<bonu> bonus { get; set; }
        public virtual DbSet<bsc_category> bsc_category { get; set; }
        public virtual DbSet<candidate_recruitment> candidate_recruitment { get; set; }
        public virtual DbSet<commission> commissions { get; set; }
        public virtual DbSet<compensation> compensations { get; set; }
        public virtual DbSet<competence> competences { get; set; }
        public virtual DbSet<competence_level> competence_level { get; set; }
        public virtual DbSet<cost_center> cost_center { get; set; }
        public virtual DbSet<cost_center_campaign> cost_center_campaign { get; set; }
        public virtual DbSet<education> educations { get; set; }
        public virtual DbSet<education_level> education_level { get; set; }
        public virtual DbSet<employee_absence> employee_absence { get; set; }
        public virtual DbSet<employee_account> employee_account { get; set; }
        public virtual DbSet<employee_bank> employee_bank { get; set; }
        public virtual DbSet<employee_basic_info> employee_basic_info { get; set; }
        public virtual DbSet<employee_campaign> employee_campaign { get; set; }
        public virtual DbSet<employee_complaint> employee_complaint { get; set; }
        public virtual DbSet<employee_contract> employee_contract { get; set; }
        public virtual DbSet<employee_emergency_contact> employee_emergency_contact { get; set; }
        public virtual DbSet<employee_experience> employee_experience { get; set; }
        public virtual DbSet<employee_identity> employee_identity { get; set; }
        public virtual DbSet<employee_out> employee_out { get; set; }
        public virtual DbSet<employee_training> employee_training { get; set; }
        public virtual DbSet<employee_training_requisition> employee_training_requisition { get; set; }
        public virtual DbSet<employee_warning> employee_warning { get; set; }
        public virtual DbSet<employement_status> employement_status { get; set; }
        public virtual DbSet<family> families { get; set; }
        public virtual DbSet<family_status> family_status { get; set; }
        public virtual DbSet<hiring_applicant> hiring_applicant { get; set; }
        public virtual DbSet<hiring_request> hiring_request { get; set; }
        public virtual DbSet<hiring_request_detail_budgeted> hiring_request_detail_budgeted { get; set; }
        public virtual DbSet<hiring_request_detail_replacement> hiring_request_detail_replacement { get; set; }
        public virtual DbSet<hiring_request_detail_unbudgeted> hiring_request_detail_unbudgeted { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<information> information { get; set; }
        public virtual DbSet<institution> institutions { get; set; }
        public virtual DbSet<institution_competence> institution_competence { get; set; }
        public virtual DbSet<institution_level> institution_level { get; set; }
        public virtual DbSet<job_interview> job_interview { get; set; }
        public virtual DbSet<job_interviewees> job_interviewees { get; set; }
        public virtual DbSet<job_interviewer> job_interviewer { get; set; }
        public virtual DbSet<job_posting_requisition> job_posting_requisition { get; set; }
        public virtual DbSet<job_repository> job_repository { get; set; }
        public virtual DbSet<job_test> job_test { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<legal_category> legal_category { get; set; }
        public virtual DbSet<level_position> level_position { get; set; }
        public virtual DbSet<loan_employee> loan_employee { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<married_status> married_status { get; set; }
        public virtual DbSet<master_tax> master_tax { get; set; }
        public virtual DbSet<medical_claim> medical_claim { get; set; }
        public virtual DbSet<mpp> mpps { get; set; }
        public virtual DbSet<mpp_approved_status> mpp_approved_status { get; set; }
        public virtual DbSet<mpp_detail> mpp_detail { get; set; }
        public virtual DbSet<mpp_status> mpp_status { get; set; }
        public virtual DbSet<nationality> nationalities { get; set; }
        public virtual DbSet<organization_job_level> organization_job_level { get; set; }
        public virtual DbSet<overtime> overtimes { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<premiaske> premiaskes { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<reimburse> reimburses { get; set; }
        public virtual DbSet<religion> religions { get; set; }
        public virtual DbSet<resignation> resignations { get; set; }
        public virtual DbSet<salary_component> salary_component { get; set; }
        public virtual DbSet<salary_process> salary_process { get; set; }
        public virtual DbSet<salary_process_component> salary_process_component { get; set; }
        public virtual DbSet<seminar> seminars { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<status_employee> status_employee { get; set; }
        public virtual DbSet<status_tax> status_tax { get; set; }
        public virtual DbSet<sub_salary_component> sub_salary_component { get; set; }
        public virtual DbSet<subgroup> subgroups { get; set; }
        public virtual DbSet<termination> terminations { get; set; }
        public virtual DbSet<training_requisition> training_requisition { get; set; }
        public virtual DbSet<transport> transports { get; set; }
        public virtual DbSet<travel> travels { get; set; }
        public virtual DbSet<travel_destination> travel_destination { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
        public virtual DbSet<vacancy_job_source> vacancy_job_source { get; set; }
        public virtual DbSet<working_effective> working_effective { get; set; }
        public virtual DbSet<account_management> account_management { get; set; }
        public virtual DbSet<approval_type> approval_type { get; set; }
        public virtual DbSet<bussiness_type> bussiness_type { get; set; }
        public virtual DbSet<campaign_progress> campaign_progress { get; set; }
        public virtual DbSet<campaign_status> campaign_status { get; set; }
        public virtual DbSet<campaign_type> campaign_type { get; set; }
        public virtual DbSet<central_resource_assigment> central_resource_assigment { get; set; }
        public virtual DbSet<channel> channels { get; set; }
        public virtual DbSet<client_brief> client_brief { get; set; }
        public virtual DbSet<client_brief_account> client_brief_account { get; set; }
        public virtual DbSet<client_brief_accountmanagement> client_brief_accountmanagement { get; set; }
        public virtual DbSet<client_brief_central_resource> client_brief_central_resource { get; set; }
        public virtual DbSet<client_brief_content> client_brief_content { get; set; }
        public virtual DbSet<client_brief_content_ref> client_brief_content_ref { get; set; }
        public virtual DbSet<client_feedback> client_feedback { get; set; }
        public virtual DbSet<dam> dams { get; set; }
        public virtual DbSet<dam_type> dam_type { get; set; }
        public virtual DbSet<job_detail> job_detail { get; set; }
        public virtual DbSet<job_pa> job_pa { get; set; }
        public virtual DbSet<job_pe> job_pe { get; set; }
        public virtual DbSet<job_status> job_status { get; set; }
        public virtual DbSet<job_status_detail> job_status_detail { get; set; }
        public virtual DbSet<job_type> job_type { get; set; }
        public virtual DbSet<job_workflow_history> job_workflow_history { get; set; }
        public virtual DbSet<job_workflow_master> job_workflow_master { get; set; }
        public virtual DbSet<job_workflow_status> job_workflow_status { get; set; }
        public virtual DbSet<master_search_content> master_search_content { get; set; }
        public virtual DbSet<pa_detail> pa_detail { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<pe_file> pe_file { get; set; }
        public virtual DbSet<pe_template> pe_template { get; set; }
        public virtual DbSet<petty_cash> petty_cash { get; set; }
        public virtual DbSet<pm> pms { get; set; }
        public virtual DbSet<proposal_file> proposal_file { get; set; }
        public virtual DbSet<propose_type> propose_type { get; set; }
        public virtual DbSet<rate_card> rate_card { get; set; }
        public virtual DbSet<rate_card_code> rate_card_code { get; set; }
        public virtual DbSet<report_file> report_file { get; set; }
        public virtual DbSet<status_assigned> status_assigned { get; set; }
        public virtual DbSet<sub_campaign> sub_campaign { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<task_comment> task_comment { get; set; }
        public virtual DbSet<task_priority> task_priority { get; set; }
        public virtual DbSet<task_status> task_status { get; set; }
        public virtual DbSet<task_timesheet> task_timesheet { get; set; }
        public virtual DbSet<task_user> task_user { get; set; }
        public virtual DbSet<company_account> company_account { get; set; }
        public virtual DbSet<departement> departements { get; set; }
        public virtual DbSet<division> divisions { get; set; }
        public virtual DbSet<employement_history> employement_history { get; set; }
        public virtual DbSet<job_grade> job_grade { get; set; }
        public virtual DbSet<job_level> job_level { get; set; }
        public virtual DbSet<job_title> job_title { get; set; }
    }
}
