//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_detail
    {
        public string id { get; set; }
        public string job_pa_id { get; set; }
        public string channel { get; set; }
        public string task_name { get; set; }
        public string services { get; set; }
        public string item { get; set; }
        public string task { get; set; }
        public string sub_task { get; set; }
        public string category { get; set; }
        public string brand { get; set; }
        public string sub_brand { get; set; }
        public string remarks { get; set; }
        public string quantity { get; set; }
        public string price_per_quantity { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
