//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_access
    {
        public string id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public string owner_id { get; set; }
        public string application_role_id { get; set; }
        public string application_entity_id { get; set; }
        public long access_create { get; set; }
        public long access_read { get; set; }
        public long access_update { get; set; }
        public long access_delete { get; set; }
        public Nullable<long> access_approve { get; set; }
        public Nullable<long> access_lock { get; set; }
        public Nullable<long> access_activate { get; set; }
        public Nullable<long> access_append { get; set; }
        public Nullable<long> access_share { get; set; }
        public Nullable<long> access_level { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual application_entity application_entity { get; set; }
        public virtual application_role application_role { get; set; }
    }
}
