//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_process
    {
        public string id { get; set; }
        public string employee_basic_info_id { get; set; }
        public string employement_status_id { get; set; }
        public string status_employee_id { get; set; }
        public Nullable<int> basic_salary { get; set; }
        public Nullable<int> transport { get; set; }
        public Nullable<int> loan { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> bruto { get; set; }
        public Nullable<int> bruto_ofyears { get; set; }
        public Nullable<int> position_cost { get; set; }
        public Nullable<int> netto { get; set; }
        public Nullable<int> netto_ofyears { get; set; }
        public Nullable<int> ptkp_ofmonths { get; set; }
        public Nullable<int> ptkp_ofyears { get; set; }
        public Nullable<int> pkp_ofyears { get; set; }
        public Nullable<int> tax_ofyears { get; set; }
        public Nullable<int> tax_ofmonths { get; set; }
        public Nullable<int> tax_no_npwp { get; set; }
        public Nullable<int> location { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string owner_id { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
